version: '3'

services:
  kubemq:
    image: kubemq/kubemq
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
      - "9091:9090"
    environment: 
      KUBEMQ_TOKEN: 074054e8-1e3c-4a76-98ac-e5597e5ac670
      METRICS_DISABLE: "false"
      METRICS_TRACING_SAMPLE : "0.1"
      METRICS_PROMETHEUS_ENABLE : "true"
      METRICS_PROMETHEUS_PATH : "/metrics"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongoexpress:
    image: mongo-express:latest
    restart: always
    ports:
    - "8082:8081"
    container_name: mongo-express
    links:
    - mongo:mongo
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      VIRTUAL_HOST: running_instance_url
      VIRTUAL_PORT: 8082

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 3001:9090
    depends_on:
      - kubemq
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:6.6.2
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
